import { useEffect, useState } from 'react'

const apiUrl = (import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8018').replace(/\/$/, '') //removes the slash from the end of the url
type Status = 'checking' | 'connected' | 'offline' //status is only allowed to be one of the these 3

export default function BackendStatus() {
  const [status, setStatus] = useState<Status>('checking') //the status tag tells typescript that it must follow the Status type defined earlier
  const [attempt, setAttempt] = useState(0)

  useEffect(() => {
    const controller = new AbortController() //gives a way to cancel the http request
    let active = true
    const timeout = window.setTimeout(() => controller.abort(), 5000) //if backend doesnt respond withing 5 sec, cancel the request
    setStatus('checking')
    async function check() {
      try {
        //signal: controller.signal connects the request to the AbortController, so when controller.abort() runs, this fetch request is cancelled
        const response = await fetch(`${apiUrl}/health`, { signal: controller.signal }) 
        if (!response.ok) throw new Error('Health request failed')
        const data: unknown = await response.json() //response generated by the backedn is typed as unknown
        if (!data || typeof data !== 'object' || !('status' in data) || data.status !== 'ok'
          || !('service' in data) || data.service !== 'fact-layer-api') {
          throw new Error('Unexpected health response')
        }
        if (active) setStatus('connected')
      } catch {
        if (active) setStatus('offline')
      } finally {
        window.clearTimeout(timeout)
      }
    }
    void check() //void check() means that we intentionally decide not to do anything about the promise returned by the async function
    return () => { active = false; controller.abort(); window.clearTimeout(timeout) }
  }, [attempt])

  return <div className={`backend-status ${status}`}>
    <span className="status-dot" aria-hidden="true" />
    <span role="status">{status === 'checking' ? 'Checking connection…' : status === 'connected' ? 'Backend connected' : 'Backend unavailable'}</span>
    {status === 'offline' && <button onClick={() => setAttempt(value => value + 1)}>Retry connection</button>}
  </div>
}
